# GitHub Copilot Inactive User Reminder Workflow
# This workflow identifies users who haven't used their Copilot license and creates reminder issues

name: Remind inactive users about GitHub Copilot license

on:
  # Run on demand (enables 'Run workflow' button on the Actions tab)
  workflow_dispatch:
  # Run the workflow every day at 9am UTC (daily schedule)
  schedule:
    - cron: '0 9 * * *'

jobs:
  check-inactive-users:
    runs-on: ubuntu-latest

    # Modify the default permissions granted to GITHUB_TOKEN
    permissions:
      contents: read
      issues: write

    steps:
      - name: Check last GitHub Copilot activity
        id: check-last-activity
        run: |
          set -euo pipefail # Enable strict error handling

          echo "🔍 Checking Copilot license usage for Luno organization..."

          # List all GitHub Copilot seat assignments for the organisation
          RESPONSE=$(gh api --paginate \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /orgs/luno/copilot/billing/seats | \
            jq -s '{ seats: map(.seats[]) }')

          echo "📊 Found $(echo "$RESPONSE" | jq '.seats | length') total Copilot licenses"

          # Calculate threshold dates once per run for consistency
          REMINDER_THRESHOLD=$(date -d "21 days ago" +%s)
          REVOCATION_THRESHOLD=$(date -d "30 days ago" +%s)

          while read -r seat; do
            LOGIN=$(echo "$seat" | jq -r '.assignee.login')
            LAST_ACTIVITY=$(echo "$seat" | jq -r '.last_activity_at')
            CREATED_AT=$(echo "$seat" | jq -r '.created_at')

            # Skip seats without a valid assignee
            if [ -z "$LOGIN" ] || [ "$LOGIN" = "null" ]; then
              echo "ℹ️  Skipping seat with no assignee"
              continue
            fi

            # List all open issues with label 'copilot-reminder' for this user
            # Check both assigned issues and issues with the user's login in the title
            EXISTING_ISSUES=$(gh issue list --repo "${{ github.repository }}" --assignee "$LOGIN" --label 'copilot-reminder' --state open --json number 2>/dev/null || echo '[]')
            TITLE_BASED_ISSUES=$(gh issue list --repo "${{ github.repository }}" --label 'copilot-reminder' --search "$LOGIN in:title" --state open --json number 2>/dev/null || echo '[]')

            # Combine both result sets and deduplicate
            COMBINED_ISSUES=$(echo "$EXISTING_ISSUES $TITLE_BASED_ISSUES" | jq -s 'add | unique_by(.number)')
            EXISTING_ISSUES="$COMBINED_ISSUES"

            # Get last activity date and convert dates to seconds since epoch for comparison
            if [ "$LAST_ACTIVITY" = "null" ]; then
              LAST_ACTIVITY_DATE=$(date -d "$CREATED_AT" +%s)
              ACTIVITY_STATUS="never used (license assigned $(date -d "$CREATED_AT" '+%Y-%m-%d'))"
              # Use creation date for never-used licenses
              REFERENCE_DATE=$LAST_ACTIVITY_DATE
            else
              LAST_ACTIVITY_DATE=$(date -d "$LAST_ACTIVITY" +%s)
              ACTIVITY_STATUS="last used $(date -d "$LAST_ACTIVITY" '+%Y-%m-%d')"
              # Use last activity date for previously used licenses
              REFERENCE_DATE=$LAST_ACTIVITY_DATE
            fi

            # Handle different stages based on inactivity duration
            if [ "$REFERENCE_DATE" -lt "$REVOCATION_THRESHOLD" ]; then
              # 30+ days inactive - revoke the seat
              echo "🚨 User $LOGIN has been inactive for 30+ days ($ACTIVITY_STATUS) - revoking seat"

              # Remove the user from Copilot
              # Temporarily relax exit-on-error for the DELETE call only
              set +e
              REVOKE_OUTPUT=$(gh api -i \
                -X DELETE \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "/orgs/luno/copilot/billing/selected_users" \
                -f selected_usernames[]="$LOGIN" 2>&1) # Redirect stderr to stdout
              REVOKE_STATUS=$?
              set -e # Re-enable exit on error

              if [ $REVOKE_STATUS -ne 0 ]; then
                STATUS_CODE=$(echo "$REVOKE_OUTPUT" | head -n1 | awk '{print $2}')
                if [ "$STATUS_CODE" = "404" ]; then
                  echo "ℹ️ User $LOGIN was already removed or not found, skipping revocation."
                else
                  echo "🚨 Error revoking Copilot seat for user $LOGIN: $REVOKE_OUTPUT"
                  exit 1 # Exit with error for other issues
                fi
              else
                echo "✅ Revoked Copilot seat for user $LOGIN"
              fi

              # Close stale reminder issues regardless of whether the seat
              # was just revoked or had already been revoked earlier
              if [ "$(echo "$EXISTING_ISSUES" | jq 'length')" -gt 0 ]; then
                while read -r issue_number; do
                  gh issue close $issue_number \
                    --repo "${{ github.repository }}" \
                    --comment "🚨 This GitHub Copilot license has been revoked due to 30 days of inactivity. If you need access again, please reach out to your team lead."
                  echo "✅ Closed issue #$issue_number with revocation notice"
                done < <(echo "$EXISTING_ISSUES" | jq -r '.[].number')
              fi

            elif [ "$REFERENCE_DATE" -lt "$REMINDER_THRESHOLD" ] && \
                 [ "$(echo "$EXISTING_ISSUES" | jq 'length')" -eq 0 ]; then
              # 21+ days inactive - send reminder
              echo "⚠️  User $LOGIN has been inactive for 21+ days ($ACTIVITY_STATUS) - creating reminder issue"

              # Try to create issue with assignee first
              set +e # Temporarily relax exit-on-error
              ASSIGNMENT_MODE="direct"

              # First try with exact username from API
              ISSUE_CREATE_OUTPUT=$(gh issue create \
                --title "Reminder about your GitHub Copilot license - $LOGIN" \
                --body "${{ vars.COPILOT_REMINDER_MESSAGE }}" \
                --repo ${{ github.repository }} \
                --label 'copilot-reminder' \
                --assignee "$LOGIN" 2>&1)
              ISSUE_CREATE_STATUS=$?

              # If assignment failed, try alternative approaches
              if [ "$ISSUE_CREATE_STATUS" -ne 0 ]; then
                echo "⚠️  Initial assignment failed for $LOGIN, trying alternatives..."

                # Try with lowercase username
                LOGIN_LOWER=$(echo "$LOGIN" | tr '[:upper:]' '[:lower:]')
                if [ "$LOGIN_LOWER" != "$LOGIN" ]; then
                  echo "🔄 Trying lowercase: $LOGIN_LOWER"
                  ISSUE_CREATE_OUTPUT=$(gh issue create \
                    --title "Reminder about your GitHub Copilot license - $LOGIN" \
                    --body "${{ vars.COPILOT_REMINDER_MESSAGE }}" \
                    --repo ${{ github.repository }} \
                    --label 'copilot-reminder' \
                    --assignee "$LOGIN_LOWER" 2>&1)
                  ISSUE_CREATE_STATUS=$?
                fi

                # If still failing, check if it's an assignment issue
                if [ "$ISSUE_CREATE_STATUS" -ne 0 ]; then
                  if echo "$ISSUE_CREATE_OUTPUT" | grep -iqE "could not assign user|not found|cannot be assigned|does not have permission|could not add assignees|resource not accessible by integration|is not a collaborator|validation failed"; then
                    echo "⚠️  Cannot assign to user $LOGIN ($(echo "$ISSUE_CREATE_OUTPUT" | head -n1 | sed 's/.*: //')), creating with mention instead"
                    ASSIGNMENT_MODE="mention"

                    # Create issue without assignee but mention the user
                    ISSUE_BODY_WITH_MENTION="👋 @$LOGIN"$'\n\n'"${{ vars.COPILOT_REMINDER_MESSAGE }}"

                    ISSUE_CREATE_OUTPUT=$(gh issue create \
                      --title "Reminder about your GitHub Copilot license - $LOGIN" \
                      --body "$ISSUE_BODY_WITH_MENTION" \
                      --repo "${{ github.repository }}" \
                      --label 'copilot-reminder' 2>&1)
                    ISSUE_CREATE_STATUS=$?
                    if [ "$ISSUE_CREATE_STATUS" -ne 0 ]; then
                      echo "🚨 Failed to create reminder issue with @mention for $LOGIN: $ISSUE_CREATE_OUTPUT"
                      set -e
                      exit 1
                    fi
                  else
                    echo "🚨 Unexpected error creating issue for $LOGIN: $ISSUE_CREATE_OUTPUT"
                    set -e
                    exit 1
                  fi
                fi
              fi

              # Success path logging based on assignment mode
              if [ "$ISSUE_CREATE_STATUS" -eq 0 ]; then
                NEW_ISSUE_URL=$(echo "$ISSUE_CREATE_OUTPUT" | tail -n 1)
                if [ "$ASSIGNMENT_MODE" = "mention" ]; then
                  echo "✅ Created reminder issue (with @mention): $NEW_ISSUE_URL"
                else
                  echo "✅ Created reminder issue (assigned to user): $NEW_ISSUE_URL"
                fi
              fi

              set -e # Re-enable exit on error

            elif [ "$REFERENCE_DATE" -ge "$REMINDER_THRESHOLD" ] && \
                 [ "$(echo "$EXISTING_ISSUES" | jq 'length')" -gt 0 ]; then
              # User became active again - close any open reminder issues
              echo "🎉 User $LOGIN became active again ($ACTIVITY_STATUS) - closing reminder issues"

              while read -r issue_number; do
                gh issue close $issue_number \
                  --repo "${{ github.repository }}" \
                  --comment "🎉 Great! This user is now actively using GitHub Copilot. Closing this reminder automatically."
                echo "✅ Closed issue #$issue_number"
              done < <(echo "$EXISTING_ISSUES" | jq -r '.[].number')
            else
              if [ "$(echo "$EXISTING_ISSUES" | jq 'length')" -gt 0 ]; then
                echo "ℹ️  User $LOGIN still has an open reminder issue ($ACTIVITY_STATUS)"
              else
                echo "✅ User $LOGIN is active ($ACTIVITY_STATUS)"
              fi
            fi
          done < <(echo "$RESPONSE" | jq -c '.seats[]')

        # Set the GH_TOKEN, required for the 'gh issue' and 'gh api' commands
        env:
          GH_TOKEN: ${{ secrets.COPILOT_UPDATE_TOKEN }}

      - name: Summary
        run: |
          echo "🎯 Copilot license management check completed"
          echo "📝 Reminder issues created for users inactive 21+ days"
          echo "🚨 Copilot seats revoked for users inactive 30+ days"
          echo "🎉 Issues automatically closed for users who became active again"
          echo "🔄 This workflow runs daily at 9am UTC"
